<a href="https://colab.research.google.com/github/komalkhatri101/Account_Closure_Prediction/blob/main/Account_Closure_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
data = pd.read_csv("Churn_Modelling.csv")

In [ ]:
x = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
lt = LabelEncoder()
x[:,2] = lt.fit_transform(x[:,2])

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer( transformers = [('encoder' , OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))


In [ ]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units = '6',activation = 'relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units = '6',activation = 'relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units = '1',activation = 'sigmoid'))

In [ ]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy' , metrics='accuracy')

In [ ]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.6854 - accuracy: 0.5874
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4999 - accuracy: 0.7925
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4426 - accuracy: 0.8084
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4213 - accuracy: 0.8210
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4079 - accuracy: 0.8227
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3955 - accuracy: 0.8321
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3834 - accuracy: 0.8407
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3726 - accuracy: 0.8474
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3650 - accuracy: 0.8515
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3602 - accura

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 500, 1, 25, 1, 1000, 7, 1, 1, 80000]])) > 0.5)

1/1 [==============================] - 0s 19ms/step
[[ True]]


In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cf = confusion_matrix(y_test,y_pred)

In [ ]:
print(cf)

[[1536   59]
 [ 207  198]]


In [ ]:
ac = accuracy_score(y_test,y_pred)
print(ac)

0.867
